### ISSUE TITLE
Allow missing or empty Aptfile?

### ISSUE THREAD

**Issue by jjb** [heroku/heroku-buildpack-apt#129]
Thanks for this awesome project!

I think it would be better if the buildpack allowed for a missing or empty Aptfile.

1. in general allows for more flexible and safe operations - no need to nail down the perfect recipe for configuring an app, just get the buildpack into place and then deploy what you need 
2. Allows for one fewer deploy and no need for a "dummy deploy" when initially setting it up.
   * Here is the smallest setup recipe currently:
     1. deploy the Aptfile
     2. add the buildpack
     4. do a "dummy deploy" of the app so it picks up the new buildpack
   * If the buildpack tolerated no Aptfile, the recipe could be:
     1. add the buildpack
     2. deploy the Aptfile
5. If an app no longer needs packages, long after initial setup by one developer, another developer might remove the Aptfile and deploy, but not know to remove the buildpack. may as well allow this to go smoothly.

thinking about this when making this recipe for using jemalloc with ruby: https://gist.github.com/jjb/9ff0d3f622c8bbe904fe7a82e35152fc#heroku

**Comment by edmorley** [comment]
Hi!

A dummy deploy isn't needed, even when the buildpack rejects an empty `Aptfile`.

ie:
1. add the buildpack
2. deploy the Aptfile

Adding a buildpack doesn't trigger a build - the buildpack only takes effect when the next build occurs.

**Comment by jjb** [comment]
🤦 🤦 🤦 

yes of course

**Comment by jjb** [comment]
(although, maybe the other things i listed are still a reason to allow an empty Aptfile?)

**Comment by colincasey** [comment]
@jjb an empty Aptfile is allowed. You'll get a [warning from the buildpack](https://github.com/heroku/heroku-buildpack-apt/blob/master/bin/compile#L32-L40) in that case but it will not fail the build.

**Comment by jjb** [comment]
got it - so empty is okay, but missing is not? https://github.com/heroku/heroku-buildpack-apt/blob/master/bin/detect

**Comment by colincasey** [comment]
That's right. It would be a violation of the [buildpack's detection contract](https://devcenter.heroku.com/articles/buildpacks#detection-failure) so that would result in an error. And we don't automatically remove buildpacks that an application has set. 

The three scenarios you listed may be easier to accommodate with [Cloud Native Buildpacks](https://blog.heroku.com/heroku-cloud-native-buildpacks) but those aren't available for use on Heroku yet. For now, if you're worried about scenario 3 happening, I'd recommend just adding a comment to the top of the `Aptfile` like:

```
#
# If you delete this file, also remember to remove the buildpack by running:
# 
#   heroku buildpacks:remove heroku-community/apt
#
```
