### ISSUE TITLE
Build fail, no Aptfile or invalid?

### ISSUE THREAD

**Issue by megatux** [heroku/heroku-buildpack-apt#132]
Hi,
  this app deployments were working fine until a couple of months ago. Now it fails. No changes on the Aptfile. Adding file content and error output:

`$ cat Aptfile`:

```
# Aptfile
libsqlite3-dev
libsqlite3-0

```

`git push -f repo-prod some_branch:master`:

```
Enumerando objetos: 12, listo.
Contando objetos: 100% (12/12), listo.
Compresión delta usando hasta 8 hilos
Comprimiendo objetos: 100% (6/6), listo.
Escribiendo objetos: 100% (8/8), 1.17 KiB | 1.17 MiB/s, listo.
Total 8 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Updated 59 paths from f6b8d12
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-22 stack
remote: -----> Using buildpacks:
remote:        1. heroku-community/apt
remote:        2. heroku/ruby
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/apt.tgz
remote:        Could not find an 'Aptfile'! Please ensure it exists and is checked into Git.
remote: 
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: e2205334116aeb2376886c5f26b8901ad93fdf1f
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version e2205334116aeb2376886c5f26b8901ad93fdf1f
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to newsan-tv.
remote: 
To https://git.heroku.com/newsan-tv.git
 ! [remote rejected] update_ruby_and_gems -> master (pre-receive hook declined)
error: falló el empuje de algunas referencias a 'https://git.heroku.com/newsan-tv.git'

```

Thx!

**Comment by megatux** [comment]
Adding more info. This happened after upgrading Ruby from ruby 3.1.3 to ruby 3.1.6(latest) and also to 3.3.2. Pushes using the same Ruby version, 3.1.1, still works.

**Comment by colincasey** [comment]
@megatux that's odd. That error message would come from [here](https://github.com/heroku/heroku-buildpack-apt/blob/master/bin/detect#L4-L10) which should not be affected in any way by Ruby version upgrades. 

The detected filename is case-sensitive though. Could the application have been using `aptfile` instead of `Aptfile`?

**Comment by megatux** [comment]
Yeah, saw that script with the error message, the file name hasn't changed, is "Aptfile". I'll try to fork the build pack later and do some tests or debug a bit.
Are there existing deployed apps using these latest ruby versions? Maybe one with an existing vm update?

**Comment by schneems** [comment]
Hello! Sorry for the issue. Can you please open a Heroku support ticket at https://help.heroku.com/ along with giving us access to the application that's experiencing this error.

Once done, please comment back here with the ticket number and we can make sure to take a look.

Also since this problem is happening on push, we don't preserve a copy of your code (on push fails) so please run this command:

```
$ git push heroku main:support
```

> Run it without the `$`, this signifies it needs to be run on the command line

This command will send the contents of your application that's on the `main` branch to the `heroku` remote and make a `support` branch that we can view.

## Quick debug

Looking at the buildpacks:

```
remote:        1. heroku-community/apt
remote:        2. heroku/ruby
```

The `heroku/ruby` buildpack is run after the apt buildpack. I don't think changing Ruby version would affect the `heroku-community/apt` buildpack because `heroku/ruby` hasn't run by the time this error occurs.

Ensure that the file exists and is checked into git. Your output should match this:

```
$ git ls-files | grep Aptfile
Aptfile
```

And you should see everything checked in:

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

And that you're on the `main` branch:

```
$ git branch
* main
...
```

(Make sure main is green and has a `*` by it)

Based on this output:

```
remote:  ! ## Warning - The same version of this code has already been built: e2205334116aeb2376886c5f26b8901ad93fdf1f
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version e2205334116aeb2376886c5f26b8901ad93fdf1f
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to newsan-tv.
```

My guess is that you're on a different branch that doesn't have an Aptfile. Either that or it got added to the .gitignore somehow or possibly the https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore. 

Anyway, this is information that might be helpful. To debug further please send us a ticket number from Heroku's support portal.

**Comment by megatux** [comment]
I tried again today, upgrading to Ruby 3.1.6 and then 3.3.3 and worked without any issues now. I guess we can close the issue. Thanks
