### ISSUE TITLE
Dependencies not being installed, mtr

### ISSUE THREAD

**Issue by tjfoster** [heroku/heroku-buildpack-apt#32]
I'm attempting to install mtr.  When I ps:exec and issue an mtr command, I get missing library errors.  As I add the missing libraries to Aptfile, I get new missing library errors.  The dependencies are deep so I could chase this all day if I have to do it manually. Is there a flag or something I can add to install the dependencies for me?

**Comment by lazyatom** [comment]
I wonder if this is related to #35 (
https://github.com/heroku/heroku-buildpack-apt/issues/35#issuecomment-415476527)

**Comment by KevinBrolly** [comment]
This is happening because the `mtr` library has multiple dependencies such as:

```
libgtk2.0-0
libxfixes3
libatk1.0-0
libxinerama1
libxi6
```

These dependencies are all available on the Heroku *build* image, but not the *runtime* image (as seen in the tables here - https://devcenter.heroku.com/articles/stack-packages). So when the application is building apt can see these packages available and therefore does not install them again, but at runtime the packages are then missing and this is why you then getting the missing library errors.

Unfortunately the only way to solve this would be to identify and install these dependencies in your Aptfile yourself.
