### ISSUE TITLE
How to specify gdal version ?

### ISSUE THREAD

**Issue by jpuaux** [heroku/heroku-buildpack-apt#54]
I would like to specify a gdal version in Aptfile but entering "gdal-bin=2.1.3" returns the following error when deployed to Heroku :
Version '2.1.3' for 'gdal-bin' was not found
Any clue ?
Thank you

**Comment by KevinBrolly** [comment]
Hi there,

By default this buildpack will only allow you to install packages available on your associated stack via the ubuntu package repository - https://packages.ubuntu.com/

Since `gdal-bin` is not available in Xenial (16.04) or Bionic (18.04) it is also not available via this buildpack, if you wanted to install `gdal-bin` you would need to create a custom buildpack to install this package.
