### ISSUE TITLE
ERROR: App not compatible with buildpack?

### ISSUE THREAD

**Issue by git-avinash** [heroku/heroku-buildpack-apt#86]
remote: -----> Building on the Heroku-20 stack
remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-apt
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed

**Comment by gersonsouto521** [comment]
Hello good morning, if you are using a pyodbc version == 4.0.30. Here is usually normally.

**Comment by Metux-renolib** [comment]
I got the same error with heroku-18, then upgraded to heroku-20 and nothing changed.

**Comment by edmorley** [comment]
Hi! When a build fails with the "App not compatible with buildpack" it means:
1. The app in question has that specific buildpack configured explicitly
2. The `bin/detect` script for that buildpack failed (exited non-zero)

ie: This is not a problem with the buildpack, but a configuration/app issue.

To resolve you need to either:
* Remove the buildpack (if it's not wanted) - eg via `heroku buildpacks:remove` or resetting buildpacks entirely via `heroku buildpacks:clear` and letting auto-detection do its thing again
* Fix the underlying issue that is causing the buildpack's `bin/detect` to fail. In the case of the APT buildpack this means you must have an `Aptfile` in the root of the repository

The UX could definitely be clearer here (eg the APT buildpack's `bin/detect` script output a more user-friendly "could not find an Aptfile" type error message), however the cause is still an app issue.
